apiVersion: apps/v1
kind: Deployment
metadata:
  generation: 1
  labels:
    app: k8s-counter-deploy
  name: k8s-counter-deploy
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: k8s-counter-deploy
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: k8s-counter-deploy
    spec:
      containers:
        - image: ghcr.io/propedeutica/elixir-k8s-counter:latest
          imagePullPolicy: Always
          name: elixir-k8s-counter
          ports:
            - containerPort: 4000
              protocol: TCP
          envFrom:
            - secretRef:
                name: secrets
          env:
            - name: PHX_HOST
              value: raspberry5b.local # Make this the IP or CNAME of the main host or LB
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
